c#_49_group_7_zhusupov_nurtegin/MobilePhones/MobliePhones/Controllers/GeometryController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using MobilePhones.Models;

namespace MobilePhones.Controllers
{
    public class GeometryController : Controller
    {
        private readonly IHostingEnvironment appEnvironment;
        public GeometryController(IHostingEnvironment appEnvironment)

        {

            this.appEnvironment = appEnvironment;

        }
        public IActionResult DownloadFile()

        {

            string filePath = Path.Combine(appEnvironment.ContentRootPath, "MyFiles/Images.pdf");

            string fileType = "application/pdf";

            string fileName = "Images.pdf";

            return PhysicalFile(filePath, fileType, fileName);

        }
        public FileResult GetFileBytes()

        {

            string path = Path.Combine(appEnvironment.ContentRootPath, "MyFiles/Images2.pdf");

            byte[] array = System.IO.File.ReadAllBytes(path);

            string fileType = "application/pdf";

            string fileName = "Images2.pdf";

            return File(array, fileType, fileName);

        }
        public FileResult GetFileStream()

        {

            string path = Path.Combine(appEnvironment.ContentRootPath, "MyFiles/Images3.pdf");

            FileStream stream = new FileStream(path, FileMode.Open);

            string fileType = "application/pdf";

            string fileName = "Images3.pdf";

            return File(stream, fileType, fileName);

        }
        public VirtualFileResult GetVirtualFile()

        {

            var filepath = Path.Combine("~/MyFiles", "Images.pdf");

            return File(filepath, "application/pdf", "Images.pdf");

        }






        public IActionResult Index(int id, int quantity, string str)
        {
            ViewBag.Id = id;
            ViewBag.Quantity = quantity;
            ViewBag.Stroka = str;
       
            return View();
        }
        [HttpPut]
        public string Square(int width, int height,string str)

        {

            ///return $" - HttpPut - Площадь прямоугольника с основанием {rectangle.Width } и высотой {rectangle.Height} равна {rectangle.CalculateSquare()}";
            double square = width * height;

            return $" -  Площадь прямоугольника с основанием {width} и высотой {height} равна {square}";
        }
        /*public IActionResult Square()

        {

            return View();

        }*/
        [HttpPost, HttpPut]
        public string Square(int width, int height)

        {

            double square = width * height;
           
           
             return $" - HttpPost - Площадь прямоугольника с основанием {width} и высотой {height} равна {square}";
            
           

        }

        public string Sum(int[] numbers)

        {

            return "Сумма чисел равна" + numbers.Sum();

        }
        public IActionResult Squares(Rectangle[] rectangles)
        {
            return View(rectangles.ToList());
        }



    }
    
}

c#_49_group_7_zhusupov_nurtegin/MobilePhones/MobliePhones/Views/Geometry/Index.cshtml
@{
    ViewData["Title"] = "Geometry Page";
}
<h1>Welcome!</h1>

<p>Id = @ViewBag.Id</p>
<p>Quantity = @ViewBag.Quantity</p>
<p>Stroka = @ViewBag.Stroka</p>

<a class="nav-link text-dark"  asp-controller="Geometry" asp-action="DownloadFile">Download PhysicalFile</a>
<br/>
<a class="nav-link text-dark" asp-controller="Geometry" asp-action="GetFileBytes">Download GetFileBytes</a>
<br />
<a class="nav-link text-dark" asp-controller="Geometry" asp-action="GetFileStream">Download GetFileStream</a>
<br />
<a class="nav-link text-dark" asp-controller="Geometry" asp-action="GetVirtualFile">Download GetVirtualFile</a>

c#_49_group_7_zhusupov_nurtegin/MobilePhones/MobliePhones/Views/Geometry/Square.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Geometry</h1>

<h4>Rectangle</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form action="/Geometry/Square" method="post">

            <div class="form-group">
                <label class="control-label" for="width">width</label>
                <input class="form-control" type="text" id="width" name="width" value="" />
            </div>
            <div class="form-group">
                <label class="control-label" for="heigth">height</label>
                <input class="form-control" type="text" id="height" name="height" value="" />
            </div>

            <div class="form-group">
                <label class="control-label" for="str">str</label>
                <input class="form-control" type="text" id="str" name="str" value="" />
            </div>

            <div class="form-group">
                <input type="submit" value="Send" class="btn btn-primary" />
            </div>

        </form>
    </div>
</div>

c#_49_group_7_zhusupov_nurtegin/MobilePhones/MobliePhones/Views/Geometry/Squares.cshtml
@{
    ViewData["Title"] = "Geometry Page";
}
@model IEnumerable<Rectangle>

@foreach (var item in Model)
{

    <div class="row">
        <div class="col-sm-6">Width: @Html.DisplayFor(modelItem => item.Width)</div>
        <div class="col-sm-6">Height: @Html.DisplayFor(modelItem => item.Height) </div>
        </div>

        }